### ISSUE TITLE
关于权重下载路径

### ISSUE THREAD

**Issue by haory-95** [CrazyBoyM/llama3-Chinese-chat#11]
小白请教一个问题，”/path/to/model'需要改成你的权重下载路径"，这句话意思是设置一个新文件夹会自动下载到里面还是存在一个权重文件要下到对应的文件夹呀？但是看了一下似乎没有找到权重文件，请指教一下，谢谢

**Comment by PCKxin** [comment]
模型文件路径
例如:
![image](https://github.com/CrazyBoyM/llama3-Chinese-chat/assets/62007403/63ef0b2a-6a76-401c-9d31-ccfe5ec8dc52)
