### ISSUE TITLE
模型选择问题

### ISSUE THREAD

**Issue by WangTianYuan** [CrazyBoyM/llama3-Chinese-chat#17]
非常感谢大佬提供的各种模型，我们正在做一个领域的RAG，知识都是中文的，如果我想要选择一个模型来做LLM的话，应该如何选择呢？现在有好多个版本，v1-v3, Instruct之类的，有哪个更适合吗？还是需要都下载下来测试？

**Comment by CrazyBoyM** [comment]
现在这几个版本都没有针对&nbsp;RAG&nbsp;场景去练，可能无法满足这个场景的需求，建议直接在原始&nbsp;base&nbsp;或者当前中文上测试还不错的&nbsp;model&nbsp;上对着&nbsp;RAG&nbsp;场景的文档问答数据先练一下，比如用&nbsp;readme&nbsp;上面的&nbsp;web-QA&nbsp;数据集


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月24日(周三) 上午9:42
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [CrazyBoyM/llama3-Chinese-chat] 模型选择问题 (Issue #17)




 
非常感谢大佬提供的各种模型，我们正在做一个领域的RAG，知识都是中文的，如果我想要选择一个模型来做LLM的话，应该如何选择呢？现在有好多个版本，v1-v3, Instruct之类的，有哪个更适合吗？还是需要都下载下来测试？
 
&mdash;

**Comment by WangTianYuan** [comment]
好的，谢谢大佬，我们的数据量比较小，我先尝试一下看看效果
