### ISSUE TITLE
感谢贡献，能够提供下训练参数和方法吗？打算着手复现学习下

### ISSUE THREAD

**Issue by zhou-wjjw** [CrazyBoyM/llama3-Chinese-chat#3]
您好，十分感谢贡献，想准备资源继续跟着项目进一步学习一下和复现，十分希望能够了解到更多一点的信息，希望得到您的回复，在此感谢。
1.训练的硬件参考算力配置
2.训练的参考时间耗费
3.训练的主要参数与方法
4.数据是否经过进一步处理

**Comment by CrazyBoyM** [comment]
后面会录制视频教程


---原始邮件---
发件人: &quot;Ahmad ***@***.***&gt;
发送时间: 2024年4月20日(周六) 晚上6:00
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [CrazyBoyM/llama3-Chinese-chat] 感谢贡献，能够提供下训练参数和方法吗？打算着手复现学习下 (Issue #3)




 
您好，十分感谢贡献，想准备资源继续跟着项目进一步学习一下和复现，十分希望能够了解到更多一点的信息，希望得到您的回复，在此感谢。
 1.训练的硬件参考算力配置
 2.训练的参考时间耗费
 3.训练的主要参数与方法
 4.数据是否经过进一步处理
 
&mdash;

**Comment by zhou-wjjw** [comment]
感谢
