### ISSUE TITLE
怎么我使用的指令版本加中文，连翻译和计算功能都丢失了？

### ISSUE THREAD

**Issue by chappyhome** [CrazyBoyM/llama3-Chinese-chat#31]
![image](https://github.com/CrazyBoyM/llama3-Chinese-chat/assets/1982081/c9591ea2-94f7-4982-a775-86ee0d45d672)

**Comment by CrazyBoyM** [comment]
是instruct + v2版本么，因为训练的中文数据集里没有包含数学计算和中英翻译的数据，如果需要的话建议自行配比相关数据～ 
如果你是要保持原版instruct能力的话，仓库最近也会推出一个只让它说中文，但不进行大量训练的权重版本
