### ISSUE TITLE
感觉不太行，输出像是一堆乱码？

### ISSUE THREAD

**Issue by lddlww** [CrazyBoyM/llama3-Chinese-chat#40]
![image](https://github.com/CrazyBoyM/llama3-Chinese-chat/assets/27006237/ff8d9d00-f90e-473f-9101-57e5915050e0)

**Comment by CrazyBoyM** [comment]
你好，你使用的是哪个模型链接？感觉是没下载完整，没有任何正常的模型会出现这个情况。

**Comment by lddlww** [comment]
谢谢回复，

我下载地址是：

```git clone https://www.modelscope.cn/baicai003/llama-3-8b-Instruct-chinese_v2.git```

```git clone https://www.modelscope.cn/baicai003/Llama3-Chinese_v2.git```

使用的是2卡 3090 ubuntu 22.04操作系统，python 3.10版本

**Comment by CrazyBoyM** [comment]
看其他网友都没有出现这个问题，是不是没下载完整，或者系统字体有缺失。感觉是tokenizer.decode以后出现了字符显示上的问题。

**Comment by lddlww** [comment]
正常没下载完整，应该是跑不起来？这个确实有点奇怪，我重新下载了几次还是一样，难道是底层的pytorch包不兼容

**Comment by CrazyBoyM** [comment]
试试用这个：https://www.suanyun.cn/console/share?uuid=b1ba51908f8a4bd1af37148765c293ee

**Comment by wantedace** [comment]
请问一下，这个问题最后怎么解决了？我在llama3.1上也遇到了同样的问题
