### ISSUE TITLE
问了几个弱智吧的问题，感觉白微调了

### ISSUE THREAD

**Issue by jiyzhang** [CrazyBoyM/llama3-Chinese-chat#42]
<img width="630" alt="image" src="https://github.com/CrazyBoyM/llama3-Chinese-chat/assets/2226524/d193c96e-0d21-4a37-bd58-d004892c5002">

**Comment by CrazyBoyM** [comment]
仓库里收录了海量版本，这是哪一个版本

**Comment by wxyttty** [comment]
![image](https://github.com/CrazyBoyM/llama3-Chinese-chat/assets/56407086/f93ce040-a520-4212-abad-49e487cec42d)
8b不知道，70b的微调没问题
