### ISSUE TITLE
Llama3-Chinese_v2版本回答很奇怪

### ISSUE THREAD

**Issue by KajiMaCN** [CrazyBoyM/llama3-Chinese-chat#47]
在docker内开启服务之后，用requests产生的回复是这样的，很奇怪
![image](https://github.com/CrazyBoyM/llama3-Chinese-chat/assets/28567261/cc7ff20a-aa9a-44c5-a624-2688a86db5fc)
![image](https://github.com/CrazyBoyM/llama3-Chinese-chat/assets/28567261/f4bbb2cf-c48a-4a59-aa37-9ae13ae8c6cd)

**Comment by CrazyBoyM** [comment]
无法对话需要设置正确的chat模板，另外文中不是乱码而是表情，linux终端的默认字体无法显示表情，实际是正常的文本
