### ISSUE TITLE
您好，我如何检验模型的上下文长度呢

### ISSUE THREAD

**Issue by lwj2001** [CrazyBoyM/llama3-Chinese-chat#56]
您好！如果按照您的方法：直接将把`config.json`中`max_position_embeddings`改为32768（32k) ，rope_theta改为1000000或者4000000
我该如何检验修改后模型的上下文长度呢？

**Comment by CrazyBoyM** [comment]
参考“大海捞针”评测

**Comment by HaoRenkk123** [comment]
请问rope_theta修改和要匹配的max_position_embeddings是否存在什么比例关系呢，如果要扩充到一个maxlen值，那rope_theta修改为多少呢，rope_scaling是否也需要修改呢
