### ISSUE TITLE
关于生成速度

### ISSUE THREAD

**Issue by ldqrecord** [CrazyBoyM/llama3-Chinese-chat#62]
请问这个生成速度感觉很慢，一秒一次的感觉，看了显存也没有超过，是为什么呢
![image](https://github.com/user-attachments/assets/851d9dae-7619-410e-b84e-f3f3704b2478)

**Comment by CrazyBoyM** [comment]
可能是显卡太差的原因？可以尝试用vllm方案跑压榨下显卡

**Comment by CrazyBoyM** [comment]
vllm部署教程：https://github.com/CrazyBoyM/llama3-Chinese-chat/tree/main/deploy/vLLM

**Comment by lhz3791** [comment]
我用的也是同样的显卡，开启4bit量化后回复速度会有显著提升。

**Comment by ldqrecord** [comment]
> 我用的同样的显卡，开启4bit解析后回复速度会有显着提升。

这个要怎么开启呢

**Comment by ldqrecord** [comment]
> vllm部署教程：https://github.com/CrazyBoyM/llama3-Chinese-chat/tree/main/deploy/vLLM

好的，已解决
